local TASK_STATUSES = igi_subtask.TASK_STATUSES
local trace_assert = igi_helper.trace_assert

Get = {}
function Get.on_init(entity)
	trace_assert(type(entity.id) == "number", "Get: entity.id is not a number", entity)
	trace_assert(alife_object(entity.id), "Get: no server object for this id", entity)
end

function Get.status(entity)
	local se_obj = alife_object(entity.id)
	if not se_obj then return TASK_STATUSES.FAILED end
	if se_obj.parent_id == 0 then return TASK_STATUSES.COMPLETED end
	return TASK_STATUSES.RUNNING
end

function Get.quest_target(obj_data)
	local se_obj = assert(alife_object(obj_data.id))
	if se_obj.parent_id == 65535 then
		return obj_data.id
	else
		return se_obj.parent_id
	end
end
