local trace_assert = igi_helper.trace_assert
local TASK_STATUSES = igi_subtask.TASK_STATUSES

local function ara_enabled()
	return igi_mcm.get_options_value("realistic_assassinations")
end

Kill = {}
function Kill.on_init(entity)
	trace_assert(type(entity.id) == "number", "Kill: entity.id is not a number", entity)
	trace_assert(alife_object(entity.id), "Kill: no server object for this id", entity)
	trace_assert(alife_object(entity.id):commander_id(), "Kill: entity.id is not a squad", entity)

	if ara_enabled() then
		entity.squads = {entity.id}
		igi_ara.Ara.on_init(entity)
	end
end

function Kill.status(entity)
	if entity.ara_to_kill and ara_enabled() then
		local ara_status = igi_ara.Ara.status(entity)
		if ara_status ~= TASK_STATUSES.COMPLETED then
			return ara_status
		end
	end
	if not alife_object(entity.id) then return TASK_STATUSES.COMPLETED end
	return TASK_STATUSES.RUNNING
end

function Kill.quest_target(entity)
	return entity.id
end

function Kill.test(entity)
	local assert_test = igi_tests.assert_test
	entity._test_stage = (entity._test_stage or 0) + 1

	if entity._test_stage == 1 then
		local se_obj = alife_object(entity.id)
		assert_test(se_obj, "Kill entity does not exist")
		assert_test(se_obj:squad_members(), "Kill entity is not a squad")
		if igi_mcm.get_options_value("fast_tests") then
			igi_tests.teleport_to_player(se_obj)
		else
			igi_tests.travel_to_se_obj(se_obj)
		end

	elseif entity._test_stage == 2 then
		local se_obj = alife_object(entity.id)
		for se_npc in se_obj:squad_members() do
			local npc = assert(get_object_by_id(se_npc.id))
			npc:kill(db.actor)
		end
		get_object_by_id(se_obj:commander_id()):kill(db.actor)

	elseif entity._test_stage == 4 then
		assert_test(entity.status == "COMPLETED", "Quest did not complete after killing")
		return true
	end
end
