TASK_STATUSES = {
	RUNNING = nil,	-- no value means running
	COMPLETED = "complete",
	FAILED = "fail",
	READY_TO_FINISH = "READY_TO_FINISH",
}

function finish_all_subtasks(CACHE)
	if CACHE.status ~= TASK_STATUSES.FAILED then
		CACHE.status = TASK_STATUSES.COMPLETED
	end

	for _, entity in pairs(CACHE.entities) do
		if entity.status == TASK_STATUSES.READY_TO_FINISH then
			entity.status = CACHE.status
		end
	end
end

function update_current_map_target(CACHE)
	if CACHE.status == TASK_STATUSES.COMPLETED
		or CACHE.status == TASK_STATUSES.READY_TO_FINISH then
		CACHE.quest_targets = {CACHE.task_giver_id}
	else
		CACHE.quest_targets = get_quest_target(CACHE.entities, CACHE)
	end
end

function process_subtasks(CACHE)
	for _, entity in pairs(CACHE.entities) do
		if update_entity_status(entity, CACHE) then
			igi_helper.trace_dbg("on_subtask_status_change", CACHE, entity)
		end
	end

	CACHE.status = get_task_status(CACHE.entities, CACHE)
	return CACHE.status
end

function get_quest_target(entities, CACHE)
	local got_first = false
	local targets = {}
	for _, entity in ipairs(entities) do
		local controller = igi_taskdata.get_controller(entity, CACHE)
		if controller.status and controller.quest_target
			and entity.status == TASK_STATUSES.RUNNING then
				if (not got_first or entity.subtask) then
					got_first = true
					targets[#targets+1] = controller.quest_target(entity)
				end
		end
	end
	return targets
end

function get_task_status(entities, CACHE)
	local ready_to_finish = false
	local running = false
	for _, entity in pairs(entities) do
		local controller = igi_taskdata.get_controller(entity, CACHE)
		if controller.status then
			if entity.status == TASK_STATUSES.FAILED and not entity.optional then
				return TASK_STATUSES.FAILED
			end
	
			if entity.status == TASK_STATUSES.RUNNING then
				running = true
			elseif entity.status == TASK_STATUSES.READY_TO_FINISH then
				ready_to_finish = true
			end
		end
	end

	if running then return TASK_STATUSES.RUNNING
	elseif ready_to_finish then return TASK_STATUSES.READY_TO_FINISH
	else return TASK_STATUSES.COMPLETED end
end

function update_entity_status(entity, CACHE)
	run_helpers(entity, CACHE, "status")

	local controller = igi_taskdata.get_controller(entity, CACHE)
	if not controller.status then return false end
	local new_status = controller.status(entity)
	if new_status == entity.status then return false end
	entity.status = new_status
	return true
end

local function get_frame_with_entities(frame, CACHE)
	if frame.entities then
		return frame
	end

	local frame_src = dup_table(igi_taskdata.get_frame(frame.src))
	if (frame_src.inputs) then
		for k, typ in pairs(frame_src.inputs) do
			local val = igi_text_processor.eval_maybe_macro(frame[k], CACHE, frame)
			igi_helper.trace_assert(val ~= nil and type(val) == typ, "Bad frame input "..k, frame, frame_src)
			frame_src.inputs[k] = val
		end
		frame_src.inputs.link_id = "inputs"

		frame_src.entities[#frame_src.entities+1] = frame_src.inputs
	end

	if (frame_src.outputs) then
		frame_src.outputs.link_id = "outputs"
		frame_src.entities[#frame_src.entities+1] = frame_src.outputs
		frame.outputs = nil
	end

	frame.entities = frame_src.entities
	igi_helper.trace_dbg("Fill frame: frame, source", frame, frame_src)
	return frame
end

local function get_next_frame(CACHE)
	if (CACHE.frames and CACHE.frames[CACHE.current_frame]) then
		local current_frame = CACHE.frames[CACHE.current_frame]
		local next_frame = igi_text_processor.eval_maybe_macro(current_frame.NEXT_FRAME, CACHE, current_frame)
		if next_frame then return next_frame end
	end
	return (CACHE.current_frame or 0) + 1
end

function activate_next_frame(CACHE)
	local new_frame = get_next_frame(CACHE)
	local frame = CACHE.frames[new_frame]
	if frame == nil then return end

	disable_entities(CACHE)

    igi_helper.trace_dbg("Enable: enable entities", new_frame, frame)
	local entities_before = frame.entities
	frame.entities = nil
	igi_text_processor.resolve_table_macros(frame, "init", igi_text_processor.get_link_context(CACHE, frame))
	frame.entities = entities_before
    get_frame_with_entities(frame, CACHE)

	-- Add and generate
    for _, entity in ipairs(frame.entities) do
        igi_helper.trace_dbg("Enable: Processing entity", entity)

        local link_context = igi_text_processor.get_link_context(frame, entity)
		igi_text_processor.resolve_table_macros(entity, "", link_context)
        local new_entities = igi_generate.generate(entity, link_context)

        for _, new_entity in ipairs(new_entities) do
            CACHE.entities[#CACHE.entities+1] = new_entity
        end
    end
	empty_table(frame.entities)

	-- Initialize
	for _, entity in ipairs(CACHE.entities) do
		local link_context = igi_text_processor.get_link_context(CACHE, entity)
		igi_text_processor.resolve_table_macros(entity, "init", link_context)

		run_helpers(entity, CACHE, "on_init")

		local controller = igi_taskdata.get_controller(entity, CACHE)
		if controller.on_init then
			controller.on_init(entity)
		end

		igi_helper.trace_dbg("on_entity_init", CACHE, entity)
	end

	process_subtasks(CACHE)
	CACHE.current_frame = new_frame
    igi_helper.trace_dbg("Enable: after run", CACHE)
	return frame
end

function disable_entities(CACHE)
	local outputs_entity
	-- De-initialize
	for i=#CACHE.entities, 1, -1 do
		local entity = CACHE.entities[i]

		local controller = igi_taskdata.get_controller(entity, CACHE)
		if controller.on_del then
			controller.on_del(entity)
		end

		run_helpers(entity, CACHE, "on_del")

		igi_text_processor.resolve_table_macros(entity, "del", igi_text_processor.get_link_context(CACHE, entity))

		if entity.link_id == "outputs" then
			outputs_entity = entity
		end
	end

	empty_table(CACHE.entities)

	local frame = CACHE.frames[CACHE.current_frame]
	if frame then
		local link_context = igi_text_processor.get_link_context(CACHE, frame)
		igi_text_processor.resolve_table_macros(frame, "del", link_context)

		if outputs_entity ~= nil then
			outputs_entity.link_id = nil
			for k, v in pairs(outputs_entity) do
				frame[k] = v
			end
		end
	end
end

function invoke_controller(callback, CACHE, ...)
	for _, entity in ipairs(CACHE.entities) do
		local controller = igi_taskdata.get_controller(entity, CACHE)
		if controller[callback] then
			controller[callback](entity, ...)
		end
	end
end

function run_helpers(entity, CACHE, method)
	for _, controller in ipairs(igi_taskdata.get_helpers(entity, CACHE)) do
		if controller[method] then
			controller[method](entity)
		end
	end
end
