local TASK_STATUSES = igi_subtask.TASK_STATUSES
local trace_assert = igi_helper.trace_assert

function on_before_hit(entity, npc, shit)
    if not entity.target_ids[npc:id()] then return end
    if shit.draftsman:id() ~= 0 then return end

    local wpn = get_object_by_id(shit.weapon_id)
    if entity.weapon and ((not wpn) or wpn:section() ~= entity.weapon) then return end

    if wpn and entity.ammo_type then
        local ammo_type_number = wpn:get_ammo_type()
        local ammo_list = utils_item.get_ammo(wpn:section(), wpn:id())
        local ammo_section = ammo_list[ammo_type_number+1]
        if ammo_section ~= entity.ammo_type then return end
    end

    entity._shot = true
    return true
end

local function get_target_ids(squad_id, only_commander)
    local se_squad = assert(alife_object(squad_id))
    local ids = {}
    ids[se_squad:commander_id()] = true
    if not only_commander then
        for npc in se_squad:squad_members() do
            ids[npc.id] = true
        end
    end
    return ids
end

Shoot = {}

function Shoot.register_callbacks(entity)
    return {
        npc_on_before_hit = on_before_hit,
        monster_on_before_hit = on_before_hit
    }
end

function Shoot.on_init(entity)
	trace_assert(type(entity.id) == "number", "Shoot: entity.id is not a number", entity)
	trace_assert(alife_object(entity.id), "Shoot: no server object for this id", entity)
	trace_assert(alife_object(entity.id):commander_id(), "Shoot: entity.id is not a squad", entity)
    entity.target_ids = get_target_ids(entity.id, entity.only_commander)
end

function Shoot.status(entity)
    if entity._shot then return TASK_STATUSES.COMPLETED, 1 end
    if not alife_object(entity.id) then return TASK_STATUSES.FAILED end
    return TASK_STATUSES.RUNNING, 0
end

function Shoot.quest_target(entity)
    return entity.id
end

function Shoot.test(entity)
	local assert_test = igi_tests.assert_test
	entity._test_stage = (entity._test_stage or 0) + 1

	if entity._test_stage == 1 then
		local se_obj = alife_object(entity.id)
		assert_test(se_obj, "Entity does not exist")
        local se_wpn = alife_create_item("wpn_mp133", alife_object(0))
        entity._test_wpn_id = se_wpn.id
        if igi_mcm.get_options_value("fast_tests") then
			igi_tests.teleport_to_player(se_obj)
		else
			igi_tests.travel_to_se_obj(se_obj)
		end

    elseif entity._test_stage == 2 then
        local obj = get_object_by_id(entity._test_wpn_id)
		db.actor:make_item_active(obj)

        local se_squad = alife_object(entity.id)
        ---@diagnostic disable-next-line: undefined-field
        alife():teleport_object(se_squad:commander_id(),db.actor:game_vertex_id(),db.actor:level_vertex_id(),db.actor:position())

	elseif entity._test_stage == 4 then
		local se_squad = alife_object(entity.id)
        local npc = assert(get_object_by_id(se_squad:commander_id()))
        local dir = npc:position():sub(db.actor:position())
        db.actor:set_actor_direction(-dir:getH())
        level.press_action(DIK_keys.MOUSE_1)
        level.release_action(DIK_keys.MOUSE_1)

    elseif entity._test_stage == 5 then
		assert_test(entity.status == "READY_TO_FINISH", "Quest did not complete")
        ---@diagnostic disable-next-line: undefined-field
        alife():release(assert(alife_object(entity._test_wpn_id)))
		return true
	end
end
