
local trace_dbg = igi_helper.trace_dbg

TEXT_HEADER = "igi_task_text_"

function get_smart_name_by_id(id)
	if tonumber(id) and SIMBOARD.smarts[id] then
		local smart = alife_object(id)
		return "st_" .. smart:name() .. "_name"
	end
end

function anomaly_name_by_binder(binder)
	local field_name = binder.ini:r_string_ex('anomal_zone',"field_name")
	igi_helper.trace_assert(field_name, "Anomaly doesn't have a field_name")
	return 'st_' .. field_name .. '_name'
end

function item_name_by_section(section_name)
	igi_helper.trace_assert(type(section_name) == "string", "section is not a string", section_name)
	return ini_sys:r_string_ex(section_name, "inv_name_short")
end

function item_name_by_id(id)
	local se_obj = alife_object(id)
	igi_helper.trace_assert(se_obj, "No server object for id", id)
	return item_name_by_section(se_obj:section_name())
end


function get_description(CACHE)
	local content = {}
	for label, v in pairs(CACHE.description or {}) do
		content[#content+1] = item_to_string(v, label)
	end

	return table.concat(content, "\\n")
end

function get_rewards_description(CACHE)
	if not igi_mcm.get_options_value("show_rewards") then return "" end
	local low = igi_rewards.get_rewards(CACHE)
	if (low.money == 0 and low.goodwill == 0) then
		return ""
	end

	return game.translate_string(TEXT_HEADER .. "rewards")
		.. ' ' ..
		tostring(low.money) ..
		" " .. game.translate_string(TEXT_HEADER .. "money") .. ", "
		.. tostring(low.goodwill) ..
		" " .. game.translate_string(TEXT_HEADER .. "goodwill")
end

function item_to_string(item, label)
	if not next(item) then return "" end

	local details = {}
	for k, v in pairs(item) do
		details[#details+1] = type(v) == "string" and game.translate_string(v) or game.translate_string(k)
	end

	label = game.translate_string(TEXT_HEADER..label)
	return label..": "..table.concat(details, ', ')
end

function show_description(CACHE)
	if not CACHE.DESCRIPTION then
		return DefaultDescription.show_description(CACHE)
	end

	local link_context = igi_text_processor.get_link_context(CACHE)
	local descr = igi_text_processor.eval_logic_macro(CACHE.DESCRIPTION, link_context)
	return descr.show_description(CACHE)
end

DefaultDescription = {}
function DefaultDescription.show_description(CACHE)
	local title, text, icon = get_task_text_values(CACHE)

	CreateTimeEvent(0, "igi_task_"..CACHE.task_id.."_setup", 0, function ()
		db.actor:give_talk_message2(title, text, icon, "iconed_answer_item")
		return true
	end)
end

function get_task_text_values(CACHE)
	local mark = igi_mcm.get_options_value("wtf_task_mark") and "[WTF] " or ""
	local title = mark .. get_task_text(CACHE.description_key, "name", CACHE.task_giver_id)
	local text = get_description(CACHE) .. "\\n" .. get_rewards_description(CACHE)
	local icon = CACHE.icon or "ui_iconsTotal_mutant"
	return title, text, icon
end

function get_task_text(desc_key, field, tg_id)
	desc_key = desc_key or ""
	local se_tg = alife_object(tg_id)
	local tg_name = se_tg:section_name() ~= "m_trader" and se_tg:section_name() or se_tg:name()

	-- returns exclusive task text if exists
	local text_id = desc_key.."_"..tg_name.."_"..field
	local text = game.translate_string(text_id)
	if text ~= text_id then return text end

	-- fallback to basic field for this task type
	local basic_text_id = desc_key.."_"..field
	text = game.translate_string(basic_text_id)
	if text ~= basic_text_id then return text end

	-- if (field ~= "done") then
	-- 	igi_helper.trace_error("No description for key: "..desc_key, text_id, basic_text_id)
	-- end
	
	-- fallback to basic field
	return game.translate_string(TEXT_HEADER..field)
end
