local trace_dbg = igi_helper.trace_dbg

function has_material_rewards(CACHE)
	return get_rewards(CACHE).money > 0
end

function get_rewards(CACHE)
	local rewards = {money = 0, goodwill = 0}
	local link_context = igi_text_processor.get_link_context(CACHE)
	for k, v in pairs(CACHE.rewards or {}) do
		if type(v) == "number" then
			rewards[k] = v
		else
			rewards[k] = igi_text_processor.eval_logic_macro(v, link_context)
		end
	end
	rewards.money = math.ceil(rewards.money
			* igi_mcm.get_options_value("money_reward_coeff")
			* igi_mcm.get_task_value(CACHE.quest_id, "money_reward_coeff"))

	rewards.goodwill = math.ceil(rewards.goodwill
			* igi_mcm.get_options_value("goodwill_reward_coeff")
			* igi_mcm.get_task_value(CACHE.quest_id, "goodwill_reward_coeff"))
	return rewards
end

function collect_and_give_rewards(CACHE)
	local rewards = get_rewards(CACHE)

	trace_dbg("rewards", rewards)
	igi_callbacks.invoke_callbacks("on_before_rewarding", CACHE, rewards)
	local faction = igi_helper.get_community_by_id(CACHE.task_giver_id)
	
	if (rewards.money ~= 0) then
		dialogs.relocate_money(db.actor, rewards.money, "in")
	end

	if (rewards.goodwill ~= 0) then
		xr_effects.inc_faction_goodwill_to_actor(db.actor, nil, { faction, rewards.goodwill, true })
	end
end
