local trace_dbg = igi_helper.trace_dbg

function has_material_rewards(CACHE)
	return get_rewards(CACHE.rewards, CACHE).money > 0
end

function get_rewards(cache_rewards, CACHE)
	local rewards = {money = 0, goodwill = 0}
	for k, v in pairs(cache_rewards or {}) do
		rewards[k] = igi_text_processor.eval_maybe_macro(v, CACHE)
	end
	rewards.money = math.ceil(rewards.money
			* igi_mcm.get_task_value(CACHE.quest_id, "money_reward_coeff"))

	rewards.goodwill = math.ceil(rewards.goodwill
			* igi_mcm.get_task_value(CACHE.quest_id, "goodwill_reward_coeff"))
	return rewards
end

function collect_and_give_rewards(CACHE)
	local rewards = get_rewards(CACHE.rewards, CACHE)

	igi_helper.trace_dbg("on_before_rewarding", CACHE, rewards)
	local faction = igi_helper.get_community_by_id(CACHE.task_giver_id)

	if (rewards.money ~= 0) then
		dialogs.relocate_money(db.actor, rewards.money, "in")
	end

	if (rewards.goodwill ~= 0) then
		xr_effects.inc_faction_goodwill_to_actor(db.actor, nil, { faction, rewards.goodwill, true })
	end
end

function give_fail_penalty(CACHE)
	local penalty = get_rewards(CACHE.fail_penalty or {
		goodwill = -30
	}, CACHE)

	igi_helper.trace_dbg("on_before_penalizing", CACHE, penalty)
	local faction = igi_helper.get_community_by_id(CACHE.task_giver_id)
	if (penalty.goodwill ~= 0) then
		xr_effects.inc_faction_goodwill_to_actor(db.actor, nil, { faction, penalty.goodwill, true })
	end
end
