function on_game_start()
	RegisterScriptCallback("npc_on_hit_callback", npc_on_hit_callback)
	RegisterScriptCallback("monster_on_hit_callback", npc_on_hit_callback)

	printf("WTF: Arszi Realistic Assassinations loaded.")
end

killed_by_player = {}

function npc_on_hit_callback(npc,amount,local_direction,who,bone_index)
	if (not npc or not who) then return end
	if (not npc.id or not who.id) then return end

	if who:id() == 0 or se_load_var(who:id(), who:name(), "companion") then
		killed_by_player[npc:id()] = true
	end
end

Ara = {}

function Ara.on_init(entity)
	igi_helper.trace_assert(type(entity.squads) == "table", "ARA: entity.squads is not a table", entity)
	for _, squad_id in pairs(entity.squads) do
		local se_squad = alife_object(squad_id)
		igi_helper.trace_assert(se_squad and se_squad.squad_members, "ARA: id is not a squad", squad_id)

		entity.ara_to_kill = {}
		for member in se_squad:squad_members() do
			entity.ara_to_kill[member.id] = true
		end
	end
end

local function all_squads_dead(entity)
	for _, id in pairs(entity.squads) do
		if alife_object(id) then
			return false
		end
	end
	return true
end

function Ara.status(entity)
	if entity.ara_status then return entity.ara_status end
	for id in pairs(entity.ara_to_kill) do
		if killed_by_player[id] then
			entity.ara_status = igi_subtask.TASK_STATUSES.COMPLETED
			return igi_subtask.TASK_STATUSES.COMPLETED
		end
	end

	if all_squads_dead(entity) then
		entity.ara_status = igi_subtask.TASK_STATUSES.FAILED
		return igi_subtask.TASK_STATUSES.FAILED
	end

	return igi_subtask.TASK_STATUSES.RUNNING
end
