local TASK_STATUSES = igi_subtask.TASK_STATUSES
local trace_assert = igi_helper.trace_assert

Return = {}
function Return.on_init(entity)
	trace_assert(type(entity.id) == "number", "Return: entity.id is not a number", entity)
	trace_assert(alife_object(entity.id), "Return: no server object for this id", entity)
end

function Return.status(entity)
	local se_obj = alife_object(entity.id)
	if not se_obj then return TASK_STATUSES.FAILED end
	if se_obj.parent_id == 0 then return TASK_STATUSES.READY_TO_FINISH end
	return TASK_STATUSES.RUNNING
end

function Return.on_complete(obj_data)
	local obj = assert(alife_object(obj_data.id))
	news_manager.relocate_item(db.actor, "out", obj:section_name(), 1)
	alife_release(obj)
end

function Return.quest_target(obj_data)
	local se_obj = alife_object(obj_data.id)
	if not se_obj then return end

	return se_obj.parent_id == 65535 and obj_data.id or se_obj.parent_id
end
