local trace_assert = igi_helper.trace_assert
MAX_DISTANCE_SQR = 2500

local function distance(position_1, position_2)
	local x = position_1.x - position_2.x
    local z = position_1.z - position_2.z
	return x*x + z*z
end

local function get_level_id(se_obj)
	---@diagnostic disable-next-line: undefined-field
	return game_graph():vertex(se_obj.m_game_vertex_id):level_id()
end

Visit = {}
function Visit.on_init(entity)
	trace_assert(type(entity.id) == "number", "Visit: entity.id is not a number", entity)
end

function Visit.status(entity)
	if entity._visited then return igi_subtask.TASK_STATUSES.COMPLETED, 1 end
	local target = alife_object(entity.id)
	if target == nil then
		return igi_subtask.TASK_STATUSES.FAILED, -1
	end

	local actor = alife_object(0)
	if get_level_id(target) ~= get_level_id(actor) then
		return igi_subtask.TASK_STATUSES.RUNNING, 0 end
	if distance(target.position, actor.position) < MAX_DISTANCE_SQR then
		entity._visited = true
		return igi_subtask.TASK_STATUSES.COMPLETED, 1
	end
    return igi_subtask.TASK_STATUSES.RUNNING, 0
end

function Visit.quest_target(entity)
	return entity.id
end
