trace_assert  = igi_helper.trace_assert

local fCache = {}
local function eval(v)
	local f = fCache[v]
	if f == nil then
		f = loadstring("return " .. v)
		fCache[v] = f
	end
	assert(f, "Function cannot be compiled: " .. (v or nil))
	return f()
end

LinkContext  = {
	_NO_THIS = {},

	new = function(self, CACHE)
		local link_context = {
			CACHE = CACHE,
			this = self._NO_THIS,
		}
		for _, entity in pairs(CACHE.entities) do
			if entity.link_id then
				trace_assert(link_context[entity.link_id] == nil, "link_id already in context", link_context, entity)
				link_context[entity.link_id] = entity
			end
		end

		for _, frame in pairs(CACHE.frames or {}) do
			if frame.link_id then
				trace_assert(link_context[frame.link_id] == nil, "link_id already in context", link_context, frame)
				link_context[frame.link_id] = frame
			end
		end
		return setmetatable(link_context, { __index = self })
	end,

	set_this = function (self, entity)
		self.this = entity or LinkContext._NO_THIS
		return self
    end,

	get = function (self, link)
		return self:get_table(link)[link.field]
	end,

	get_table = function (self, link)
		local tbl = self[link.link_id]
        igi_helper.trace_assert(tbl, "Linker can't find tbl for link:", link, self)
		return tbl
	end,
}

Link = {
	new = function (link_id, field)
		local t = {
			link_id = link_id,
			field = field,
		}

		return setmetatable(t, {__index = Link})
    end,

	from_str = function (self, str)
		local link_id, field = str:match("%|([^%.]+)%.(.+)%|")
		trace_assert(link_id and field, "Link can't be resolved: " .. str)
		return Link.new(link_id, field)
	end,

	remap_this = function (self, mapping)
        if mapping and self.link_id == "this" then
            self.link_id = mapping
        end
		return self
	end
}

Macro       = {
	link_context = {},
	link_pattern = "%b||",

    new = function(self, str)
		if type(str) ~= "string" then return end
        local level, is_auto, macro = string.match(str, "([^%$%@%>]*)([%@%>]?)%$(.*)")
        if not macro then return end

        local t = {
            level = level ~= '?' and level or '',
            is_auto = is_auto ~= '',
			is_effect = is_auto == '>',
			is_nullable = level == '?',
            macro = macro,
			orig = str
        }

        return setmetatable(t, { __index = self })
    end,

	_without_links = function (self)
        return string.gsub(self.macro, "%b||", function(dep)
            local link = Link:from_str(dep)
			igi_helper.trace_assert(LinkContext.get(Macro.link_context, link) ~= nil, "Value for a link can't be found!", dep, Macro.link_context)
			return "igi_text_processor.Macro.link_context." .. link.link_id .. '.' .. link.field
		end)
	end,

    resolve = function(self, link_context)
		local do_log = string.find(self.orig, '%(') -- if macro calls functions
		if do_log then
			igi_helper.trace_dbg("Resolving macro", self.orig)
		end

		Macro.link_context = link_context
		local out = eval(self:_without_links())

		if out == nil and not self.is_effect then
			trace_assert(self.is_nullable, "Macro returned nil", self.orig)
			igi_helper.trace_dbg("Failed macro resolution: macro returned nil", self.orig)
			return nil, true
		end
		trace_assert(self.is_auto or type(out) ~= "userdata", "Macro returned userdata", self.orig)

		if do_log then
			igi_helper.trace_dbg(
			"Resolved macro to", self.orig, type(out) == "userdata" and "userdata" or out)
		end
		return out
    end,

	assert_level = function (self, level)
		local is_empty_auto = self.is_auto and self.level == ""
		igi_helper.trace_assert(self.level == level or is_empty_auto, "Macro is of wrong level", level, self.orig)
		return self
	end,

	assert_not_effect = function (self)
		igi_helper.trace_assert(not self.is_effect, "Cannot link to effect macro", level, self.orig)
		return self
	end,

	link_iterator = function (self)
		return string.gmatch(self.macro, Macro.link_pattern)
	end
}

-- Careful if you want to cache it: generate step invalidates link context
function get_link_context(CACHE, entity)
	return LinkContext:new(CACHE):set_this(entity)
end

function has_macro(str)
    return Macro:new(str) ~= nil
end

local function resolve_macros(tbl, level, link_context, transient_fields)
    for k, v in pairs(tbl) do
        if type(v) == 'table' then
            resolve_macros(v, level, link_context, transient_fields)
        elseif type(v) == 'string' then
            local macro = Macro:new(v)
			if (macro and macro.level == level and (level ~= "" or not macro.is_auto)) then
				if (macro.is_auto) then
					transient_fields[tbl] = transient_fields[tbl] or {}
					transient_fields[tbl][k] = tbl[k]
				end
				local out, failed = _resolve_linked_macro(macro, level, link_context, transient_fields)
				if failed then return true end
				tbl[k] = out
			end
        end
    end
end

local function collect_links(macro, link_context, buf, this_mapping)
	igi_helper.trace_assert(#buf < 10000, "Overflow while resolving macro (>10000 links). Circular dependency?", macro)

	for dep in macro:link_iterator() do
        local link = Link:from_str(dep):remap_this(this_mapping)

		buf[#buf + 1] = link
        local val = link_context:get(link)

        local macro = Macro:new(val)
        if macro then
            collect_links(macro, link_context, buf, link.link_id)
        end
    end
    return buf
end

local function resolve_all_links(links, level, link_context, transient_fields)
	for i = #links, 1, -1 do
        local link = links[i]
        local tbl = link_context:get_table(link)
        local before = tbl[link.field]
        igi_helper.trace_assert(before ~= nil, "Link is nil", link)

        local macro = Macro:new(before)
        if macro then
            macro:assert_level(level):assert_not_effect()
			local this_before = link_context.this
			local out, failed = macro:resolve(link_context:set_this(tbl))
			if failed then
				return true
			end
			link_context:set_this(this_before)

			if macro.is_auto then
				transient_fields[tbl] = transient_fields[tbl] or {}
				transient_fields[tbl][link.field] = before
			end

			tbl[link.field] = out
        end
	end
end

function _resolve_linked_macro(macro, level, link_context, transient_fields)
    local links = collect_links(macro, link_context, {})
    local failed = resolve_all_links(links, level, link_context, transient_fields)
	if failed then
		return nil, true
	end
    return macro:resolve(link_context)
end

local function reset_transient_fields(transient_fields)
	for tbl, fields in pairs(transient_fields) do
		for k, v in pairs(fields) do
			tbl[k] = v
		end
	end
end

function resolve_table_macros(tbl, level, link_context)
	local transient_fields = {}
	local failed = resolve_macros(tbl, level, link_context, transient_fields)
	reset_transient_fields(transient_fields)
	return failed
end

function resolve_and_link_cache(CACHE, level)
    local link_context = igi_text_processor.get_link_context(CACHE)
	local transient_fields = {}

    for _, entity in pairs(CACHE.entities) do
        local failed = resolve_macros(entity, level, link_context:set_this(entity), transient_fields)
		if failed then
			reset_transient_fields(transient_fields)
			return true
		end
    end

	for _, frame in pairs(CACHE.frames) do
        local failed = resolve_macros(frame, level, link_context:set_this(frame), transient_fields)
		if failed then
			reset_transient_fields(transient_fields)
			return true
		end
    end

	local failed = resolve_macros(CACHE, level, link_context, transient_fields)
	reset_transient_fields(transient_fields)
	return failed
end

function eval_logic_macro(str, link_context, maybe)
    local macro = Macro:new(str)
	if not (macro and macro.is_auto and macro.level == '') then
		trace_assert(maybe, "Not a @$ macro", str)
		return str
	end
	local transient_fields = {}
    local resolved, failed = _resolve_linked_macro(macro, '', link_context, transient_fields)
	reset_transient_fields(transient_fields)
	return resolved, failed
end

function eval_maybe_macro(val, CACHE, this_entity)
	if type(val) ~= "string" then return val end
	local link_context = get_link_context(CACHE, this_entity)
	return eval_logic_macro(val, link_context, true)
end

function linkup_string(str, link_context)
	links = {}
	for dep in string.gmatch(str, Macro.link_pattern) do
		local link = Link:from_str(dep)

		links[#links + 1] = link
		local val = link_context:get(link)

		local macro = Macro:new(val)
		if macro then
			collect_links(macro, link_context, links, link.link_id)
		end
	end

	local transient_fields = {}
	resolve_all_links(links, "", link_context, transient_fields)
	local out = string.gsub(str, Macro.link_pattern, function(dep)
		local link = Link:from_str(dep)
		igi_helper.trace_dbg("linkup_string", link, link_context)
		return tostring(link_context[link.link_id][link.field])
	end)
	reset_transient_fields(transient_fields)
	return out
end
--------------- Testing --------------------------
--[[
igi_helper = {
  trace_assert = function(...) return assert(...) end,
  trace_dbg = print
}

loadstring = load

_G.igi_text_processor = _G

trace_assert  = igi_helper.trace_assert

CACHE = {
  entities = {
    {
    id = 1234,
    huh = '@$ |this.id|',
    br1 = "@$ |this.id|",
    br3 = "$ |this.br2|",
    br2 = "$ |this.br1|",
    brbrbr = "$ |this.br3|",
    str = "@$ |this.brbrbr|"
  }
  }
}

resolve_and_link_cache(CACHE, '')
print(eval_logic_macro(CACHE.entities[1].str, get_link_context(CACHE, CACHE.entities[1])))
print(CACHE.entities[1].br1)
]]