function keys(tbl)
    local out = {}
    for k in pairs(tbl) do
        out[#out+1] = k
    end
    return out
end

function values(tbl)
    local out = {}
    for _, v in pairs(tbl) do
        out[#out+1] = v
    end
    return out
end

function flat_map(tbl, f)
    local out = {}
    for _, v in ipairs(tbl) do
        local fout = f(v)
        for _, v2 in ipairs(fout) do
            out[#out+1] = v2
        end
    end
    return out
end

function map(tbl, f)
    local out = {}
    for _, v in ipairs(tbl) do
        out[#out+1] = f(v)
    end
    return out
end

function filter(tbl, f)
    local out = {}
    for _, v in ipairs(tbl) do
        if f(v) then
            out[#out+1] = v
        end
    end
    return out
end

function set(tbl, k, v)
    tbl[k] = v
    return v
end

function shuffle(tbl)
    local t = dup_table(tbl)
    for i = 1, #t, 1 do
        local index = igi_random.rand(i)
        t[index], t[i] = t[i], t[index]
    end
    return t
end

function iter_size(iter)
    local count = 0
    for _ in iter do
        count = count + 1
    end
    return count
end

function extend(tbl, tbl2)
    for _, v in ipairs(tbl2) do
        tbl[#tbl + 1] = v
    end
    return tbl
end

ScriptedSquad = {
    on_init = function (entity)
        igi_helper.trace_assert(type(entity.id) == "number", "id is not a number", entity)
        local se_obj = alife_object(entity.id)

        igi_helper.trace_assert(se_obj ~= nil, "no server object for given id", entity)

        se_obj.force_online = true
        sim_offline_combat.task_squads[entity.id] = true

        entity._squad_members = {}
        for se_member in se_obj:squad_members() do
            entity._squad_members[#entity._squad_members + 1] = se_member.id
            se_save_var(se_member.id, nil, "dont_release", true)
        end
    end,

    on_del = function (entity)
        sim_offline_combat.task_squads[entity.id] = nil

        local se_obj = alife_object(entity.id)
        if se_obj then
            se_obj.force_online = false
        end

        for _, id in pairs(entity._squad_members) do
            se_save_var(id, nil, "dont_release", nil)
        end
    end
}

PinToSmart = {
    on_init = function (entity)
        local se_obj = alife_object(entity.id)
        if se_obj then
            se_obj.scripted_target = se_obj.smart_id
        end
    end,

    status = function (entity)
        local se_obj = alife_object(entity.id)
        if se_obj then
            se_obj.stay_time = game.get_game_time()
        end
    end,

    on_del = function (entity)
        local se_obj = alife_object(entity.id)
        if se_obj then
            se_obj.scripted_target = nil
        end
    end
}

MapIcon = function (mark)
    return {
        status = function (entity)
            local has_spot = level.map_has_object_spot(entity.id, mark) == 1
            local se_obj = alife_object(entity.id)
            local object_in_world = se_obj and se_obj.parent_id == 65535

            if object_in_world and not has_spot then
                level.map_add_object_spot(entity.id, mark, game.translate_string(mark))
            elseif (not object_in_world) and has_spot then
                level.map_remove_object_spot(entity.id, mark)
            end
        end,

        on_del = function (entity)
            level.map_remove_object_spot(entity.id, mark)
        end
    }
end


local function is_online(id)
	local se_obj = alife_object(id)
	if not se_obj then return end

	if se_obj.squad_members then
		se_obj = se_obj:squad_members()()	-- stateful iterator, returns function
		for _,v in ipairs(db.OnlineStalkers) do
			if (v == se_obj.id) then
				return true
			end
		end
		return false
	end
	return se_obj.online
end

ChangeFaction = function (faction)
    return {
        status = function (entity)
            if entity._changefaction_done then return end
            if is_online(entity.id) then
                local se_squad = alife_object(entity.id)
                if not se_squad or not se_squad.squad_members then return end
                for npc in se_squad:squad_members() do
                    local member = get_object_by_id(npc.id)
                    if member then
                        member:set_character_community(faction, 0, 0)
                    end
                end

                entity._changefaction_done = true
            end
        end
    }
end

Repair = function (new_condition)
    return {
        status = function (entity)
            if entity._repair_done then return end
            local item = get_object_by_id(entity.id)
            if not item then return false end
            if item:condition() < (new_condition / 100) then
                get_object_by_id(entity.id):set_condition(new_condition)
                entity._repair_done = true
            end
        end
    }
end

Dead = {
    on_init = function(entity)
        igi_helper.trace_assert(type(entity.id) == "number", "id is not a number", entity)
        local se_obj = alife_object(entity.id)

        igi_helper.trace_assert(se_obj ~= nil, "no server object for given id", entity)
        igi_helper.trace_assert(se_obj.squad_members, "server object is not a squad", entity)
        entity._dead_npcs = {}
    end,

    status = function(entity)
        if not is_online(entity.id) then return end
        local se_squad = alife_object(entity.id)
        if not se_squad or not se_squad.squad_members then return end

        local members = {}
        for se_member in se_squad:squad_members() do
            members[#members + 1] = se_member
        end

        for _, se_member in pairs(members) do
            local npc = get_object_by_id(se_member.id)
            if npc then
                npc:kill(npc)
                se_save_var(se_member.id, nil, "dont_release", true)
                entity._dead_npcs[#entity._dead_npcs + 1] = se_member.id
            end
        end
    end,

    on_del = function(entity)
        if not entity._dead_npcs then return end
        for _, id in pairs(entity._dead_npcs) do
            se_save_var(id, nil, "dont_release", nil)
        end
    end
}
