function on_game_start()
    RegisterScriptCallback("actor_on_interaction", actor_on_interaction)
    RegisterScriptCallback("on_before_level_changing", function () level_change = true end)
    RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
    RegisterScriptCallback("save_state", save_state)
    RegisterScriptCallback("load_state", load_state)
end

level_change = false
function save_state(m_data)
    m_data.wtf_community_level_change = level_change
end

function load_state(m_data)
    level_change = m_data.wtf_community_level_change
end

function actor_on_first_update()
    if level_change then
        CreateTimeEvent('wtf_community', 'update_level_orders', 15, function ()
            on_level_changing_army()
            on_level_changing_duty()
            return true
        end)
    end
    level_change = false
end

function on_level_changing_army()
    local tg = get_story_se_object("agr_smart_terrain_1_6_near_2_military_colonel_kovalski")
    local task_id = tg and igi_task_manager.validate_task({"community", "orders_army"}, tg.id)
    if task_id then
        task_manager.get_task_manager():give_task(task_id)
        news_manager.send_tip(db.actor, "igi_task_text_community_orders_army_about", nil, tg, 10000)
    end
end

function on_level_changing_duty()
    local tg = get_story_se_object("bar_dolg_general_petrenko_stalker")
    local task_id = tg and igi_task_manager.validate_task({"community", "orders_duty"}, tg.id)
    if task_id then
        task_manager.get_task_manager():give_task(task_id)
        news_manager.send_tip(db.actor, "igi_task_text_community_orders_duty_about", nil, tg, 10000)
    end
end
